services:
    rabbitmq:
        image: rabbitmq:3.8
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - culinary_network

    # 1. База данных для Identity Service
    identity-db:
        image: postgres:16-alpine
        container_name: identity_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: identity_db
        ports:
            - '5432:5432' # Стандартный порт для авторизации
        volumes:
            - identity_data:/var/lib/postgresql/data
        networks:
            - culinary_network

    # 2. База данных для Recipe Service
    recipe-db:
        image: postgres:16-alpine
        container_name: recipe_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: recipes_db
        ports:
            - '5433:5432' # Внешний порт 5433
        volumes:
            - recipe_data:/var/lib/postgresql/data
        networks:
            - culinary_network

    # 3. База данных для Social Service
    social-db:
        image: postgres:16-alpine
        container_name: social_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: social_db
        ports:
            - '5434:5432' # Внешний порт 5434
        volumes:
            - social_data:/var/lib/postgresql/data
        networks:
            - culinary_network

    # 4. База данных для Media Service (Метаданные)
    media-db:
        image: postgres:16-alpine
        container_name: media_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: media_db
        ports:
            - '5435:5432' # Внешний порт 5435
        volumes:
            - media_data:/var/lib/postgresql/data
        networks:
            - culinary_network

networks:
    culinary_network:
        driver: bridge

volumes:
    identity_data:
    recipe_data:
    social_data:
    media_data:
