openapi: 3.0.3

info:
  title: Recipe Platform Internal API
  version: 1.0.0

servers:
  - url: http://auth-service:8081
  - url: http://recipe-service:8082
  - url: http://comment-service:8083

paths:

  /internal/users/{id}:
    get:
      summary: Получить пользователя
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Пользователь найден

        '404':
          description: Пользователь не найден

  /internal/recipes/{id}:
    get:
      summary: Получить рецепт
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Рецепт найден

        '404':
          description: Рецепт не найден

  /internal/comments/recipe/{id}:
    get:
      summary: Получить комментарии рецепта
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Комментарии получены