services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres52
      POSTGRES_DB: restaurant_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 2

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres52
      DB_DATABASE: restaurant_booking
      JWT_SECRET: uqvwyervuywevyuewfvuyefwuvy1337
      JWT_EXPIRES_IN: 24h
      REFRESH_TOKEN_SECRET: asdbhjasdhjbsadhjasdnjkasd67
      REFRESH_TOKEN_EXPIRES_IN: 7d
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  postgres_data:
