services:
  auth-db:
    image: postgres
    restart: always
    ports:
      - 15431:5432
    volumes:
      - ./dbs/auth-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  profile-db:
    image: postgres
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ./dbs/profile-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  resume-db:
    image: postgres
    restart: always
    ports:
      - 15433:5432
    volumes:
      - ./dbs/resume-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  vacancy-db:
    image: postgres
    restart: always
    ports:
      - 15434:5432
    volumes:
      - ./dbs/vacancy-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vacancy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  application-db:
    image: postgres
    restart: always
    ports:
      - 15435:5432
    volumes:
      - ./dbs/application-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: application_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  reference-db:
    image: postgres
    restart: always
    ports:
      - 15436:5432
    volumes:
      - ./dbs/reference-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reference_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
