services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ./dbs/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maindb
      POSTGRES_USER: maindb
      POSTGRES_PASSWORD: maindb
