name: lab2-microservices

services:
  auth-service:
    build: ./src/auth-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@auth-db:5432/auth_db
    depends_on:
      - auth-db
    networks:
      - backend-network

  job-service:
    build: ./src/job-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@job-db:5432/job_db
    depends_on:
      - job-db
    networks:
      - backend-network

  candidate-service:
    build: ./src/candidate-service
    ports:
      - "8083:8083"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@cand-db:5432/cand_db
    depends_on:
      - cand-db
    networks:
      - backend-network

  interaction-service:
    build: ./src/interaction-service
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@inter-db:5432/inter_db
    depends_on:
      - inter-db
    networks:
      - backend-network

  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: postgres
    networks:
      - backend-network

  job-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: job_db
      POSTGRES_PASSWORD: postgres
    networks:
      - backend-network

  cand-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cand_db
      POSTGRES_PASSWORD: postgres
    networks:
      - backend-network

  inter-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: inter_db
      POSTGRES_PASSWORD: postgres
    networks:
      - backend-network

networks:
  backend-network:
