events { worker_connections 1024; }
http {
    upstream auth { server auth-service:8081; }
    upstream job { server job-service:8082; }
    upstream cand { server candidate-service:8083; }
    upstream inter { server interaction-service:8084; }
    server {
        listen 80;
        location /auth/ { proxy_pass http://auth/; }
        location /jobs/ { proxy_pass http://job/; }
        location /candidates/ { proxy_pass http://cand/; }
        location /interactions/ { proxy_pass http://inter/; }
    }
}