version: '3.8'

services:
  order-db:
    image: postgres:15-alpine
    container_name: order_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5436:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

volumes:
  order_db_data: