server:
  port: 8084

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_local
    username: storage
    password: storage
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: storage
    password: storage
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: non_null

services:
  booking-base-url: http://localhost:8083
  identity-base-url: http://localhost:8081

messaging:
  review-events:
    publish-delay-ms: 3000
