server:
  port: 8084

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_local
    username: storage
    password: storage
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: non_null

services:
  booking-base-url: http://localhost:8083
