version: '3.8'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: rentease-swagger
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml