services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: maindb
      POSTGRES_PASSWORD: maindb
    volumes:
      - ./docker/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
      - ./dbs/postgres-data:/var/lib/postgresql/data
