services:
  postgres:
    image: postgres:18
    container_name: lab1-postgres
    environment:
      POSTGRES_DB: job_search
      POSTGRES_USER: job_search
      POSTGRES_PASSWORD: job_search
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U job_search -d job_search"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
