spring:
  config:
    import: optional:classpath:common-lib-application.yaml
  application:
    name: user-service
  datasource:
    url: ${USER_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/user_service}
    username: ${USER_SERVICE_DB_USERNAME:${DB_USERNAME:postgres}}
    password: ${USER_SERVICE_DB_PASSWORD:${DB_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
