server:
  port: 8082

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_local?currentSchema=catalog
    username: storage
    password: storage
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: catalog
    liquibase-schema: catalog
  jackson:
    default-property-inclusion: non_null
