services:
  postgres:
    image: postgres:16-alpine
    container_name: rental_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rental_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rental_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rental_backend
    ports:
      - "8080:8080"
    environment:
      ENV: docker
      WEB_PORT: :8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rental_db
      DB_SSLMODE: disable
      JWT_SECRET: supersecretkey
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
