spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/me/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/properties/*/bookings/*/payments, /api/v1/properties/*/bookings/*/payments/**

            - id: booking-service
              uri: lb://booking-service
              predicates:
               - Path=/api/v1/properties/*/bookings/**, /api/v1/bookings/**


            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/api/v1/properties/*/reviews, /api/v1/properties/*/reviews/**

            - id: property-service
              uri: lb://property-service
              predicates:
                - Path=/api/v1/properties/**

            - id: chat-service
              uri: lb://chat-service
              predicates:
               - Path=/api/v1/chats/**

          discovery:
            locator:
              enabled: on


server:
  port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka
logging:

  pattern:
        console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
  level:
    org.springframework.cloud.gateway:
    org.springframework.web:
