server:
  port: 8080

spring:
  application:
    name: restaurant-booking-api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_local?currentSchema=storage
    username: storage
    password: storage
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: storage
    liquibase-schema: storage
  jooq:
    sql-dialect: postgres
  jackson:
    default-property-inclusion: non_null

app:
  jwt:
    issuer: ${APP_JWT_ISSUER:restaurant-booking-api}
    access-token-ttl-minutes: ${APP_JWT_ACCESS_TOKEN_TTL_MINUTES:120}
    secret: ${APP_JWT_SECRET:restaurant-booking-local-dev-secret-key-2026}
