// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: property_public.proto

package propertypb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_property_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PropertyType  string                 `protobuf:"bytes,5,opt,name=property_type,json=propertyType,proto3" json:"property_type,omitempty"`
	PricePerNight float64                `protobuf:"fixed64,6,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Address       *string                `protobuf:"bytes,9,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Lat           *float64               `protobuf:"fixed64,10,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,11,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	Rooms         *int32                 `protobuf:"varint,12,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Beds          *int32                 `protobuf:"varint,13,opt,name=beds,proto3,oneof" json:"beds,omitempty"`
	MaxGuests     int32                  `protobuf:"varint,14,opt,name=max_guests,json=maxGuests,proto3" json:"max_guests,omitempty"`
	AreaM2        *float64               `protobuf:"fixed64,15,opt,name=area_m2,json=areaM2,proto3,oneof" json:"area_m2,omitempty"`
	CheckInTime   *string                `protobuf:"bytes,16,opt,name=check_in_time,json=checkInTime,proto3,oneof" json:"check_in_time,omitempty"`
	CheckOutTime  *string                `protobuf:"bytes,17,opt,name=check_out_time,json=checkOutTime,proto3,oneof" json:"check_out_time,omitempty"`
	Rules         *string                `protobuf:"bytes,18,opt,name=rules,proto3,oneof" json:"rules,omitempty"`
	Status        string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_property_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{1}
}

func (x *Property) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Property) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Property) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Property) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Property) GetPropertyType() string {
	if x != nil {
		return x.PropertyType
	}
	return ""
}

func (x *Property) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *Property) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Property) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Property) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Property) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Property) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *Property) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *Property) GetBeds() int32 {
	if x != nil && x.Beds != nil {
		return *x.Beds
	}
	return 0
}

func (x *Property) GetMaxGuests() int32 {
	if x != nil {
		return x.MaxGuests
	}
	return 0
}

func (x *Property) GetAreaM2() float64 {
	if x != nil && x.AreaM2 != nil {
		return *x.AreaM2
	}
	return 0
}

func (x *Property) GetCheckInTime() string {
	if x != nil && x.CheckInTime != nil {
		return *x.CheckInTime
	}
	return ""
}

func (x *Property) GetCheckOutTime() string {
	if x != nil && x.CheckOutTime != nil {
		return *x.CheckOutTime
	}
	return ""
}

func (x *Property) GetRules() string {
	if x != nil && x.Rules != nil {
		return *x.Rules
	}
	return ""
}

func (x *Property) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Property) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Property) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PropertyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Property            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyListResponse) Reset() {
	*x = PropertyListResponse{}
	mi := &file_property_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyListResponse) ProtoMessage() {}

func (x *PropertyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyListResponse.ProtoReflect.Descriptor instead.
func (*PropertyListResponse) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{2}
}

func (x *PropertyListResponse) GetItems() []*Property {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PropertyListResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FavoriteListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Property            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteListResponse) Reset() {
	*x = FavoriteListResponse{}
	mi := &file_property_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteListResponse) ProtoMessage() {}

func (x *FavoriteListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteListResponse.ProtoReflect.Descriptor instead.
func (*FavoriteListResponse) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{3}
}

func (x *FavoriteListResponse) GetItems() []*Property {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyRequest) Reset() {
	*x = GetPropertyRequest{}
	mi := &file_property_public_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyRequest) ProtoMessage() {}

func (x *GetPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{4}
}

func (x *GetPropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type ListPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          *string                `protobuf:"bytes,1,opt,name=city,proto3,oneof" json:"city,omitempty"`
	PropertyType  *string                `protobuf:"bytes,2,opt,name=property_type,json=propertyType,proto3,oneof" json:"property_type,omitempty"`
	PriceMin      *float64               `protobuf:"fixed64,3,opt,name=price_min,json=priceMin,proto3,oneof" json:"price_min,omitempty"`
	PriceMax      *float64               `protobuf:"fixed64,4,opt,name=price_max,json=priceMax,proto3,oneof" json:"price_max,omitempty"`
	Rooms         *int32                 `protobuf:"varint,5,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	MaxGuests     *int32                 `protobuf:"varint,6,opt,name=max_guests,json=maxGuests,proto3,oneof" json:"max_guests,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesRequest) Reset() {
	*x = ListPropertiesRequest{}
	mi := &file_property_public_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesRequest) ProtoMessage() {}

func (x *ListPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesRequest.ProtoReflect.Descriptor instead.
func (*ListPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{5}
}

func (x *ListPropertiesRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *ListPropertiesRequest) GetPropertyType() string {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return ""
}

func (x *ListPropertiesRequest) GetPriceMin() float64 {
	if x != nil && x.PriceMin != nil {
		return *x.PriceMin
	}
	return 0
}

func (x *ListPropertiesRequest) GetPriceMax() float64 {
	if x != nil && x.PriceMax != nil {
		return *x.PriceMax
	}
	return 0
}

func (x *ListPropertiesRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *ListPropertiesRequest) GetMaxGuests() int32 {
	if x != nil && x.MaxGuests != nil {
		return *x.MaxGuests
	}
	return 0
}

func (x *ListPropertiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPropertiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMyPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyPropertiesRequest) Reset() {
	*x = ListMyPropertiesRequest{}
	mi := &file_property_public_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyPropertiesRequest) ProtoMessage() {}

func (x *ListMyPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyPropertiesRequest.ProtoReflect.Descriptor instead.
func (*ListMyPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{6}
}

func (x *ListMyPropertiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMyPropertiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PropertyType  string                 `protobuf:"bytes,3,opt,name=property_type,json=propertyType,proto3" json:"property_type,omitempty"`
	PricePerNight float64                `protobuf:"fixed64,4,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	MaxGuests     int32                  `protobuf:"varint,6,opt,name=max_guests,json=maxGuests,proto3" json:"max_guests,omitempty"`
	Address       *string                `protobuf:"bytes,7,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Rooms         *int32                 `protobuf:"varint,8,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Beds          *int32                 `protobuf:"varint,9,opt,name=beds,proto3,oneof" json:"beds,omitempty"`
	AreaM2        *float64               `protobuf:"fixed64,10,opt,name=area_m2,json=areaM2,proto3,oneof" json:"area_m2,omitempty"`
	CheckInTime   *string                `protobuf:"bytes,11,opt,name=check_in_time,json=checkInTime,proto3,oneof" json:"check_in_time,omitempty"`
	CheckOutTime  *string                `protobuf:"bytes,12,opt,name=check_out_time,json=checkOutTime,proto3,oneof" json:"check_out_time,omitempty"`
	Rules         *string                `protobuf:"bytes,13,opt,name=rules,proto3,oneof" json:"rules,omitempty"`
	AmenityIds    []string               `protobuf:"bytes,14,rep,name=amenity_ids,json=amenityIds,proto3" json:"amenity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePropertyRequest) Reset() {
	*x = CreatePropertyRequest{}
	mi := &file_property_public_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyRequest) ProtoMessage() {}

func (x *CreatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyRequest.ProtoReflect.Descriptor instead.
func (*CreatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePropertyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePropertyRequest) GetPropertyType() string {
	if x != nil {
		return x.PropertyType
	}
	return ""
}

func (x *CreatePropertyRequest) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *CreatePropertyRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreatePropertyRequest) GetMaxGuests() int32 {
	if x != nil {
		return x.MaxGuests
	}
	return 0
}

func (x *CreatePropertyRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *CreatePropertyRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *CreatePropertyRequest) GetBeds() int32 {
	if x != nil && x.Beds != nil {
		return *x.Beds
	}
	return 0
}

func (x *CreatePropertyRequest) GetAreaM2() float64 {
	if x != nil && x.AreaM2 != nil {
		return *x.AreaM2
	}
	return 0
}

func (x *CreatePropertyRequest) GetCheckInTime() string {
	if x != nil && x.CheckInTime != nil {
		return *x.CheckInTime
	}
	return ""
}

func (x *CreatePropertyRequest) GetCheckOutTime() string {
	if x != nil && x.CheckOutTime != nil {
		return *x.CheckOutTime
	}
	return ""
}

func (x *CreatePropertyRequest) GetRules() string {
	if x != nil && x.Rules != nil {
		return *x.Rules
	}
	return ""
}

func (x *CreatePropertyRequest) GetAmenityIds() []string {
	if x != nil {
		return x.AmenityIds
	}
	return nil
}

type UpdatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PricePerNight *float64               `protobuf:"fixed64,4,opt,name=price_per_night,json=pricePerNight,proto3,oneof" json:"price_per_night,omitempty"`
	City          *string                `protobuf:"bytes,5,opt,name=city,proto3,oneof" json:"city,omitempty"`
	MaxGuests     *int32                 `protobuf:"varint,6,opt,name=max_guests,json=maxGuests,proto3,oneof" json:"max_guests,omitempty"`
	Rooms         *int32                 `protobuf:"varint,7,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Status        *string                `protobuf:"bytes,8,opt,name=status,proto3,oneof" json:"status,omitempty"`
	AmenityIds    []string               `protobuf:"bytes,9,rep,name=amenity_ids,json=amenityIds,proto3" json:"amenity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePropertyRequest) Reset() {
	*x = UpdatePropertyRequest{}
	mi := &file_property_public_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropertyRequest) ProtoMessage() {}

func (x *UpdatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropertyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *UpdatePropertyRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdatePropertyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePropertyRequest) GetPricePerNight() float64 {
	if x != nil && x.PricePerNight != nil {
		return *x.PricePerNight
	}
	return 0
}

func (x *UpdatePropertyRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdatePropertyRequest) GetMaxGuests() int32 {
	if x != nil && x.MaxGuests != nil {
		return *x.MaxGuests
	}
	return 0
}

func (x *UpdatePropertyRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *UpdatePropertyRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdatePropertyRequest) GetAmenityIds() []string {
	if x != nil {
		return x.AmenityIds
	}
	return nil
}

type DeletePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePropertyRequest) Reset() {
	*x = DeletePropertyRequest{}
	mi := &file_property_public_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePropertyRequest) ProtoMessage() {}

func (x *DeletePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePropertyRequest.ProtoReflect.Descriptor instead.
func (*DeletePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_property_public_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{10}
}

func (x *AddFavoriteRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type RemoveFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_property_public_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveFavoriteRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type Favorite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PropertyId    string                 `protobuf:"bytes,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Favorite) Reset() {
	*x = Favorite{}
	mi := &file_property_public_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Favorite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favorite) ProtoMessage() {}

func (x *Favorite) ProtoReflect() protoreflect.Message {
	mi := &file_property_public_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favorite.ProtoReflect.Descriptor instead.
func (*Favorite) Descriptor() ([]byte, []int) {
	return file_property_public_proto_rawDescGZIP(), []int{12}
}

func (x *Favorite) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Favorite) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *Favorite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_property_public_proto protoreflect.FileDescriptor

const file_property_public_proto_rawDesc = "" +
	"\n" +
	"\x15property_public.proto\x12\x0epropertypublic\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\x8f\x06\n" +
	"\bProperty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rproperty_type\x18\x05 \x01(\tR\fpropertyType\x12&\n" +
	"\x0fprice_per_night\x18\x06 \x01(\x01R\rpricePerNight\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x1d\n" +
	"\aaddress\x18\t \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x15\n" +
	"\x03lat\x18\n" +
	" \x01(\x01H\x01R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\v \x01(\x01H\x02R\x03lon\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\f \x01(\x05H\x03R\x05rooms\x88\x01\x01\x12\x17\n" +
	"\x04beds\x18\r \x01(\x05H\x04R\x04beds\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"max_guests\x18\x0e \x01(\x05R\tmaxGuests\x12\x1c\n" +
	"\aarea_m2\x18\x0f \x01(\x01H\x05R\x06areaM2\x88\x01\x01\x12'\n" +
	"\rcheck_in_time\x18\x10 \x01(\tH\x06R\vcheckInTime\x88\x01\x01\x12)\n" +
	"\x0echeck_out_time\x18\x11 \x01(\tH\aR\fcheckOutTime\x88\x01\x01\x12\x19\n" +
	"\x05rules\x18\x12 \x01(\tH\bR\x05rules\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"\n" +
	"\b_addressB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lonB\b\n" +
	"\x06_roomsB\a\n" +
	"\x05_bedsB\n" +
	"\n" +
	"\b_area_m2B\x10\n" +
	"\x0e_check_in_timeB\x11\n" +
	"\x0f_check_out_timeB\b\n" +
	"\x06_rules\"\x82\x01\n" +
	"\x14PropertyListResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.propertypublic.PropertyR\x05items\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.propertypublic.PaginationR\n" +
	"pagination\"F\n" +
	"\x14FavoriteListResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.propertypublic.PropertyR\x05items\"5\n" +
	"\x12GetPropertyRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\"\xdb\x02\n" +
	"\x15ListPropertiesRequest\x12\x17\n" +
	"\x04city\x18\x01 \x01(\tH\x00R\x04city\x88\x01\x01\x12(\n" +
	"\rproperty_type\x18\x02 \x01(\tH\x01R\fpropertyType\x88\x01\x01\x12 \n" +
	"\tprice_min\x18\x03 \x01(\x01H\x02R\bpriceMin\x88\x01\x01\x12 \n" +
	"\tprice_max\x18\x04 \x01(\x01H\x03R\bpriceMax\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\x05 \x01(\x05H\x04R\x05rooms\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_guests\x18\x06 \x01(\x05H\x05R\tmaxGuests\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offsetB\a\n" +
	"\x05_cityB\x10\n" +
	"\x0e_property_typeB\f\n" +
	"\n" +
	"_price_minB\f\n" +
	"\n" +
	"_price_maxB\b\n" +
	"\x06_roomsB\r\n" +
	"\v_max_guests\"G\n" +
	"\x17ListMyPropertiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xaa\x04\n" +
	"\x15CreatePropertyRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rproperty_type\x18\x03 \x01(\tR\fpropertyType\x12&\n" +
	"\x0fprice_per_night\x18\x04 \x01(\x01R\rpricePerNight\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"max_guests\x18\x06 \x01(\x05R\tmaxGuests\x12\x1d\n" +
	"\aaddress\x18\a \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\b \x01(\x05H\x01R\x05rooms\x88\x01\x01\x12\x17\n" +
	"\x04beds\x18\t \x01(\x05H\x02R\x04beds\x88\x01\x01\x12\x1c\n" +
	"\aarea_m2\x18\n" +
	" \x01(\x01H\x03R\x06areaM2\x88\x01\x01\x12'\n" +
	"\rcheck_in_time\x18\v \x01(\tH\x04R\vcheckInTime\x88\x01\x01\x12)\n" +
	"\x0echeck_out_time\x18\f \x01(\tH\x05R\fcheckOutTime\x88\x01\x01\x12\x19\n" +
	"\x05rules\x18\r \x01(\tH\x06R\x05rules\x88\x01\x01\x12\x1f\n" +
	"\vamenity_ids\x18\x0e \x03(\tR\n" +
	"amenityIdsB\n" +
	"\n" +
	"\b_addressB\b\n" +
	"\x06_roomsB\a\n" +
	"\x05_bedsB\n" +
	"\n" +
	"\b_area_m2B\x10\n" +
	"\x0e_check_in_timeB\x11\n" +
	"\x0f_check_out_timeB\b\n" +
	"\x06_rules\"\x98\x03\n" +
	"\x15UpdatePropertyRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12+\n" +
	"\x0fprice_per_night\x18\x04 \x01(\x01H\x02R\rpricePerNight\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x05 \x01(\tH\x03R\x04city\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_guests\x18\x06 \x01(\x05H\x04R\tmaxGuests\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\a \x01(\x05H\x05R\x05rooms\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\b \x01(\tH\x06R\x06status\x88\x01\x01\x12\x1f\n" +
	"\vamenity_ids\x18\t \x03(\tR\n" +
	"amenityIdsB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_price_per_nightB\a\n" +
	"\x05_cityB\r\n" +
	"\v_max_guestsB\b\n" +
	"\x06_roomsB\t\n" +
	"\a_status\"8\n" +
	"\x15DeletePropertyRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\"5\n" +
	"\x12AddFavoriteRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\"8\n" +
	"\x15RemoveFavoriteRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\"\x7f\n" +
	"\bFavorite\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vproperty_id\x18\x02 \x01(\tR\n" +
	"propertyId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xd6\b\n" +
	"\x0fPropertyService\x12y\n" +
	"\x0eListProperties\x12%.propertypublic.ListPropertiesRequest\x1a$.propertypublic.PropertyListResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/properties\x12u\n" +
	"\vGetProperty\x12\".propertypublic.GetPropertyRequest\x1a\x18.propertypublic.Property\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/properties/{property_id}\x12p\n" +
	"\x0eCreateProperty\x12%.propertypublic.CreatePropertyRequest\x1a\x18.propertypublic.Property\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/properties\x12~\n" +
	"\x0eUpdateProperty\x12%.propertypublic.UpdatePropertyRequest\x1a\x18.propertypublic.Property\"+\x82\xd3\xe4\x93\x02%:\x01*2 /api/v1/properties/{property_id}\x12y\n" +
	"\x0eDeleteProperty\x12%.propertypublic.DeletePropertyRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"* /api/v1/properties/{property_id}\x12\x86\x01\n" +
	"\x10ListMyProperties\x12'.propertypublic.ListMyPropertiesRequest\x1a$.propertypublic.PropertyListResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/users/me/properties\x12h\n" +
	"\rListFavorites\x12\x16.google.protobuf.Empty\x1a$.propertypublic.FavoriteListResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/favorites\x12w\n" +
	"\vAddFavorite\x12\".propertypublic.AddFavoriteRequest\x1a\x18.propertypublic.Favorite\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/favorites/{property_id}\x12x\n" +
	"\x0eRemoveFavorite\x12%.propertypublic.RemoveFavoriteRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/favorites/{property_id}B\x18Z\x16internal/pb/propertypbb\x06proto3"

var (
	file_property_public_proto_rawDescOnce sync.Once
	file_property_public_proto_rawDescData []byte
)

func file_property_public_proto_rawDescGZIP() []byte {
	file_property_public_proto_rawDescOnce.Do(func() {
		file_property_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_property_public_proto_rawDesc), len(file_property_public_proto_rawDesc)))
	})
	return file_property_public_proto_rawDescData
}

var file_property_public_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_property_public_proto_goTypes = []any{
	(*Pagination)(nil),              // 0: propertypublic.Pagination
	(*Property)(nil),                // 1: propertypublic.Property
	(*PropertyListResponse)(nil),    // 2: propertypublic.PropertyListResponse
	(*FavoriteListResponse)(nil),    // 3: propertypublic.FavoriteListResponse
	(*GetPropertyRequest)(nil),      // 4: propertypublic.GetPropertyRequest
	(*ListPropertiesRequest)(nil),   // 5: propertypublic.ListPropertiesRequest
	(*ListMyPropertiesRequest)(nil), // 6: propertypublic.ListMyPropertiesRequest
	(*CreatePropertyRequest)(nil),   // 7: propertypublic.CreatePropertyRequest
	(*UpdatePropertyRequest)(nil),   // 8: propertypublic.UpdatePropertyRequest
	(*DeletePropertyRequest)(nil),   // 9: propertypublic.DeletePropertyRequest
	(*AddFavoriteRequest)(nil),      // 10: propertypublic.AddFavoriteRequest
	(*RemoveFavoriteRequest)(nil),   // 11: propertypublic.RemoveFavoriteRequest
	(*Favorite)(nil),                // 12: propertypublic.Favorite
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_property_public_proto_depIdxs = []int32{
	13, // 0: propertypublic.Property.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: propertypublic.Property.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: propertypublic.PropertyListResponse.items:type_name -> propertypublic.Property
	0,  // 3: propertypublic.PropertyListResponse.pagination:type_name -> propertypublic.Pagination
	1,  // 4: propertypublic.FavoriteListResponse.items:type_name -> propertypublic.Property
	13, // 5: propertypublic.Favorite.created_at:type_name -> google.protobuf.Timestamp
	5,  // 6: propertypublic.PropertyService.ListProperties:input_type -> propertypublic.ListPropertiesRequest
	4,  // 7: propertypublic.PropertyService.GetProperty:input_type -> propertypublic.GetPropertyRequest
	7,  // 8: propertypublic.PropertyService.CreateProperty:input_type -> propertypublic.CreatePropertyRequest
	8,  // 9: propertypublic.PropertyService.UpdateProperty:input_type -> propertypublic.UpdatePropertyRequest
	9,  // 10: propertypublic.PropertyService.DeleteProperty:input_type -> propertypublic.DeletePropertyRequest
	6,  // 11: propertypublic.PropertyService.ListMyProperties:input_type -> propertypublic.ListMyPropertiesRequest
	14, // 12: propertypublic.PropertyService.ListFavorites:input_type -> google.protobuf.Empty
	10, // 13: propertypublic.PropertyService.AddFavorite:input_type -> propertypublic.AddFavoriteRequest
	11, // 14: propertypublic.PropertyService.RemoveFavorite:input_type -> propertypublic.RemoveFavoriteRequest
	2,  // 15: propertypublic.PropertyService.ListProperties:output_type -> propertypublic.PropertyListResponse
	1,  // 16: propertypublic.PropertyService.GetProperty:output_type -> propertypublic.Property
	1,  // 17: propertypublic.PropertyService.CreateProperty:output_type -> propertypublic.Property
	1,  // 18: propertypublic.PropertyService.UpdateProperty:output_type -> propertypublic.Property
	14, // 19: propertypublic.PropertyService.DeleteProperty:output_type -> google.protobuf.Empty
	2,  // 20: propertypublic.PropertyService.ListMyProperties:output_type -> propertypublic.PropertyListResponse
	3,  // 21: propertypublic.PropertyService.ListFavorites:output_type -> propertypublic.FavoriteListResponse
	12, // 22: propertypublic.PropertyService.AddFavorite:output_type -> propertypublic.Favorite
	14, // 23: propertypublic.PropertyService.RemoveFavorite:output_type -> google.protobuf.Empty
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_property_public_proto_init() }
func file_property_public_proto_init() {
	if File_property_public_proto != nil {
		return
	}
	file_property_public_proto_msgTypes[1].OneofWrappers = []any{}
	file_property_public_proto_msgTypes[5].OneofWrappers = []any{}
	file_property_public_proto_msgTypes[7].OneofWrappers = []any{}
	file_property_public_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_property_public_proto_rawDesc), len(file_property_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_property_public_proto_goTypes,
		DependencyIndexes: file_property_public_proto_depIdxs,
		MessageInfos:      file_property_public_proto_msgTypes,
	}.Build()
	File_property_public_proto = out.File
	file_property_public_proto_goTypes = nil
	file_property_public_proto_depIdxs = nil
}
