// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: property.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyRequest) Reset() {
	*x = GetPropertyRequest{}
	mi := &file_property_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyRequest) ProtoMessage() {}

func (x *GetPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{0}
}

func (x *GetPropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type PropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PricePerNight float64                `protobuf:"fixed64,3,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyResponse) Reset() {
	*x = PropertyResponse{}
	mi := &file_property_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyResponse) ProtoMessage() {}

func (x *PropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyResponse.ProtoReflect.Descriptor instead.
func (*PropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PropertyResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PropertyResponse) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *PropertyResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PropertyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListIDsByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIDsByOwnerRequest) Reset() {
	*x = ListIDsByOwnerRequest{}
	mi := &file_property_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIDsByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIDsByOwnerRequest) ProtoMessage() {}

func (x *ListIDsByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIDsByOwnerRequest.ProtoReflect.Descriptor instead.
func (*ListIDsByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{2}
}

func (x *ListIDsByOwnerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListIDsByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyIds   []string               `protobuf:"bytes,1,rep,name=property_ids,json=propertyIds,proto3" json:"property_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIDsByOwnerResponse) Reset() {
	*x = ListIDsByOwnerResponse{}
	mi := &file_property_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIDsByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIDsByOwnerResponse) ProtoMessage() {}

func (x *ListIDsByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIDsByOwnerResponse.ProtoReflect.Descriptor instead.
func (*ListIDsByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{3}
}

func (x *ListIDsByOwnerResponse) GetPropertyIds() []string {
	if x != nil {
		return x.PropertyIds
	}
	return nil
}

var File_property_proto protoreflect.FileDescriptor

const file_property_proto_rawDesc = "" +
	"\n" +
	"\x0eproperty.proto\x12\bproperty\"5\n" +
	"\x12GetPropertyRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\"\x93\x01\n" +
	"\x10PropertyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12&\n" +
	"\x0fprice_per_night\x18\x03 \x01(\x01R\rpricePerNight\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"2\n" +
	"\x15ListIDsByOwnerRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\";\n" +
	"\x16ListIDsByOwnerResponse\x12!\n" +
	"\fproperty_ids\x18\x01 \x03(\tR\vpropertyIds2\xac\x01\n" +
	"\x10PropertyInternal\x12C\n" +
	"\aGetByID\x12\x1c.property.GetPropertyRequest\x1a\x1a.property.PropertyResponse\x12S\n" +
	"\x0eListIDsByOwner\x12\x1f.property.ListIDsByOwnerRequest\x1a .property.ListIDsByOwnerResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_property_proto_rawDescOnce sync.Once
	file_property_proto_rawDescData []byte
)

func file_property_proto_rawDescGZIP() []byte {
	file_property_proto_rawDescOnce.Do(func() {
		file_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)))
	})
	return file_property_proto_rawDescData
}

var file_property_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_property_proto_goTypes = []any{
	(*GetPropertyRequest)(nil),     // 0: property.GetPropertyRequest
	(*PropertyResponse)(nil),       // 1: property.PropertyResponse
	(*ListIDsByOwnerRequest)(nil),  // 2: property.ListIDsByOwnerRequest
	(*ListIDsByOwnerResponse)(nil), // 3: property.ListIDsByOwnerResponse
}
var file_property_proto_depIdxs = []int32{
	0, // 0: property.PropertyInternal.GetByID:input_type -> property.GetPropertyRequest
	2, // 1: property.PropertyInternal.ListIDsByOwner:input_type -> property.ListIDsByOwnerRequest
	1, // 2: property.PropertyInternal.GetByID:output_type -> property.PropertyResponse
	3, // 3: property.PropertyInternal.ListIDsByOwner:output_type -> property.ListIDsByOwnerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_property_proto_init() }
func file_property_proto_init() {
	if File_property_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_property_proto_goTypes,
		DependencyIndexes: file_property_proto_depIdxs,
		MessageInfos:      file_property_proto_msgTypes,
	}.Build()
	File_property_proto = out.File
	file_property_proto_goTypes = nil
	file_property_proto_depIdxs = nil
}
