// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: property.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropertyInternal_GetByID_FullMethodName        = "/property.PropertyInternal/GetByID"
	PropertyInternal_ListIDsByOwner_FullMethodName = "/property.PropertyInternal/ListIDsByOwner"
)

// PropertyInternalClient is the client API for PropertyInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PropertyInternal — внутренний gRPC-сервис property-service.
// Используется booking-service для получения данных об объектах.
type PropertyInternalClient interface {
	// GetByID — получить объект по ID (цена, владелец).
	GetByID(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	// ListIDsByOwner — получить список ID объектов владельца.
	ListIDsByOwner(ctx context.Context, in *ListIDsByOwnerRequest, opts ...grpc.CallOption) (*ListIDsByOwnerResponse, error)
}

type propertyInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyInternalClient(cc grpc.ClientConnInterface) PropertyInternalClient {
	return &propertyInternalClient{cc}
}

func (c *propertyInternalClient) GetByID(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyInternal_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyInternalClient) ListIDsByOwner(ctx context.Context, in *ListIDsByOwnerRequest, opts ...grpc.CallOption) (*ListIDsByOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIDsByOwnerResponse)
	err := c.cc.Invoke(ctx, PropertyInternal_ListIDsByOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyInternalServer is the server API for PropertyInternal service.
// All implementations must embed UnimplementedPropertyInternalServer
// for forward compatibility.
//
// PropertyInternal — внутренний gRPC-сервис property-service.
// Используется booking-service для получения данных об объектах.
type PropertyInternalServer interface {
	// GetByID — получить объект по ID (цена, владелец).
	GetByID(context.Context, *GetPropertyRequest) (*PropertyResponse, error)
	// ListIDsByOwner — получить список ID объектов владельца.
	ListIDsByOwner(context.Context, *ListIDsByOwnerRequest) (*ListIDsByOwnerResponse, error)
	mustEmbedUnimplementedPropertyInternalServer()
}

// UnimplementedPropertyInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyInternalServer struct{}

func (UnimplementedPropertyInternalServer) GetByID(context.Context, *GetPropertyRequest) (*PropertyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedPropertyInternalServer) ListIDsByOwner(context.Context, *ListIDsByOwnerRequest) (*ListIDsByOwnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIDsByOwner not implemented")
}
func (UnimplementedPropertyInternalServer) mustEmbedUnimplementedPropertyInternalServer() {}
func (UnimplementedPropertyInternalServer) testEmbeddedByValue()                          {}

// UnsafePropertyInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyInternalServer will
// result in compilation errors.
type UnsafePropertyInternalServer interface {
	mustEmbedUnimplementedPropertyInternalServer()
}

func RegisterPropertyInternalServer(s grpc.ServiceRegistrar, srv PropertyInternalServer) {
	// If the following call panics, it indicates UnimplementedPropertyInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyInternal_ServiceDesc, srv)
}

func _PropertyInternal_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyInternalServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyInternal_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyInternalServer).GetByID(ctx, req.(*GetPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyInternal_ListIDsByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIDsByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyInternalServer).ListIDsByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyInternal_ListIDsByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyInternalServer).ListIDsByOwner(ctx, req.(*ListIDsByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyInternal_ServiceDesc is the grpc.ServiceDesc for PropertyInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.PropertyInternal",
	HandlerType: (*PropertyInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByID",
			Handler:    _PropertyInternal_GetByID_Handler,
		},
		{
			MethodName: "ListIDsByOwner",
			Handler:    _PropertyInternal_ListIDsByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "property.proto",
}
