services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: restaurant-booking-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: storage
      RABBITMQ_DEFAULT_PASS: storage
