classDiagram
  Recipe --> User : author_id
  Recipe --> DishType : dish_type_id
  SavedRecipe --> User : user_id
  SavedRecipe --> Recipe : recipe_id
  Subscription --> User : subscriber_id
  Subscription --> User : subscribed_to_id
  Comment --> User : user_id
  Comment --> Recipe : recipe_id
  RecipeIngredient --> Recipe : recipe_id
  RecipeIngredient --> Ingredient : ingredient_id
  RecipeIngredient --> Unit : unit_id
  CommentLike --> User : user_id
  CommentLike --> Comment : comment_id
  RecipeRating --> User : user_id
  RecipeRating --> Recipe : recipe_id
  RecipeStep --> Recipe : recipe_id
  RecipeStepMedia --> RecipeStep : recipe_step_id
  RecipeMedia --> Recipe : recipe_id

  class User {
    PK id
    first_name: VARCHAR
    last_name: VARCHAR
    bio: TEXT
    username: VARCHAR
    role: ENUM(USER, ADMIN)
    email: VARCHAR
    password: VARCHAR
    updated_at: TIMESTAMP
    created_at: TIMESTAMP
    is_verified: BOOLEAN
  }
  class Recipe {
    PK id
    FK author_id
    FK dish_type_id
    title: VARCHAR
    description: TEXT
    difficulty: ENUM(HARD, MEDIUM, EASY)
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
    is_published: BOOLEAN
  }
  class SavedRecipe {
    PK id
    FK user_id
    FK recipe_id
    saved_at: TIMESTAMP
  }
  class Subscription {
    PK id
    FK subscriber_id
    FK subscribed_to_id
    subscribed_at: TIMESTAMP
  }
  class DishType {
    PK id
    title: VARCHAR
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
  }
  class Comment {
    PK id
    FK user_id
    FK recipe_id
    text: TEXT
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
  }
  class Ingredient {
    PK id
    title: VARCHAR
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
  }
  class RecipeIngredient {
    PK id
    FK ingredient_id
    FK recipe_id
    FK unit_id
    quantity: NUMERIC
    alt_unit_text: VARCHAR
    preparation_note: VARCHAR
  }
  class CommentLike {
    PK id
    FK user_id
    FK comment_id
    liked_at: TIMESTAMP
  }
  class RecipeRating {
    PK id
    FK user_id
    FK recipe_id
    rating: INT
    rated_at: TIMESTAMP
  }
  class RecipeStep {
    PK id
    FK recipe_id
    number: INT
    title: VARCHAR
    description: TEXT
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
  }
  class RecipeStepMedia {
    PK id
    FK recipe_step_id
    sort_order: INT
    media_type: ENUM(PHOTO, VIDEO)
    media_url: VARCHAR
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
  }
  class Unit {
    PK id
    title: VARCHAR
    abbreviation: VARCHAR
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
  }
  class RecipeMedia {
    PK id
    FK recipe_id
    sort_order: INT
    media_type: ENUM(PHOTO, VIDEO)
    media_url: VARCHAR
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
  }
