spring:
  config:
    import: optional:classpath:common-lib-application.yaml
  application:
    name: progress-service
  datasource:
    url: ${PROGRESS_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/progress_service}
    username: ${PROGRESS_SERVICE_DB_USERNAME:${DB_USERNAME:postgres}}
    password: ${PROGRESS_SERVICE_DB_PASSWORD:${DB_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:fitness}
    password: ${RABBITMQ_PASSWORD:fitness}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  integration:
    training-service:
      base-url: ${TRAINING_SERVICE_BASE_URL:http://training-service:8080/api/v1}
