version: '3.8'

services:
  company-db:
    image: postgres:15-alpine
    container_name: company_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: company_db
    ports:
      - "5435:5432"
    volumes:
      - company_db_data:/var/lib/postgresql/data

volumes:
  company_db_data: