server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_local?currentSchema=identity
    username: storage
    password: storage
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: identity
    liquibase-schema: identity
  jackson:
    default-property-inclusion: non_null
