CREATE SEQUENCE IF NOT EXISTS seq_refresh_token START WITH 1 INCREMENT BY 5;

CREATE SEQUENCE IF NOT EXISTS user_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE _user_
(
    id            BIGINT                      NOT NULL,
    global_role   VARCHAR(255)                NOT NULL,
    is_renter     BOOLEAN,
    is_landlord   BOOLEAN,
    username      VARCHAR(255)                NOT NULL,
    password_hash VARCHAR(255)                NOT NULL,
    email         VARCHAR(255)                NOT NULL,
    phone_number  VARCHAR(20),
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    patronymic    VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk__user_ PRIMARY KEY (id)
);

CREATE TABLE amenity
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_amenity PRIMARY KEY (id)
);

CREATE TABLE booking
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    renter_id      BIGINT                                  NOT NULL,
    property_id    BIGINT                                  NOT NULL,
    payment_id     BIGINT,
    start_date     date                                    NOT NULL,
    end_date       date                                    NOT NULL,
    booking_status VARCHAR(255)                            NOT NULL,
    total_price    DOUBLE PRECISION                        NOT NULL,
    guests_count   INTEGER,
    details        VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE chat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user1id_id BIGINT                                  NOT NULL,
    user2id_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

CREATE TABLE message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id_id BIGINT                                  NOT NULL,
    chat_id      BIGINT                                  NOT NULL,
    message      VARCHAR(255)                            NOT NULL,
    timestamp    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount         DOUBLE PRECISION                        NOT NULL,
    payed_at       TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    payment_status VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE property
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255),
    total_reviews  INTEGER,
    rating_sum     INTEGER,
    avg_rating     DOUBLE PRECISION,
    price          FLOAT                                   NOT NULL,
    square         FLOAT                                   NOT NULL,
    type           VARCHAR(255)                            NOT NULL,
    country        VARCHAR(255)                            NOT NULL,
    region         VARCHAR(255)                            NOT NULL,
    city           VARCHAR(255)                            NOT NULL,
    street         VARCHAR(255)                            NOT NULL,
    postal_code    VARCHAR(255)                            NOT NULL,
    main_image     VARCHAR(255)                            NOT NULL,
    nearest_subway VARCHAR(255),
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    available      BOOLEAN,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_property PRIMARY KEY (id)
);

CREATE TABLE property_amenity_link
(
    amenity_id  BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    CONSTRAINT pk_property_amenity_link PRIMARY KEY (amenity_id, property_id)
);

CREATE TABLE property_image
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    url         VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_property_image PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id         BIGINT                      NOT NULL,
    token      VARCHAR(255)                NOT NULL,
    user_id    BIGINT                      NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked    BOOLEAN,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE review
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id_id     BIGINT                                  NOT NULL,
    property_id_id BIGINT                                  NOT NULL,
    rating         INTEGER                                 NOT NULL,
    comment        VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

ALTER TABLE _user_
    ADD CONSTRAINT uc__user__email UNIQUE (email);

ALTER TABLE _user_
    ADD CONSTRAINT uc__user__username UNIQUE (username);

ALTER TABLE amenity
    ADD CONSTRAINT uc_amenity_name UNIQUE (name);

ALTER TABLE booking
    ADD CONSTRAINT uc_booking_payment UNIQUE (payment_id);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_token UNIQUE (token);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payment (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_RENTER FOREIGN KEY (renter_id) REFERENCES _user_ (id);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_USER1ID FOREIGN KEY (user1id_id) REFERENCES _user_ (id);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_USER2ID FOREIGN KEY (user2id_id) REFERENCES _user_ (id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_SENDERID FOREIGN KEY (sender_id_id) REFERENCES _user_ (id);

ALTER TABLE property_image
    ADD CONSTRAINT FK_PROPERTY_IMAGE_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE property
    ADD CONSTRAINT FK_PROPERTY_ON_USER FOREIGN KEY (user_id) REFERENCES _user_ (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES _user_ (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_PROPERTYID FOREIGN KEY (property_id_id) REFERENCES property (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_USERID FOREIGN KEY (user_id_id) REFERENCES _user_ (id);

ALTER TABLE property_amenity_link
    ADD CONSTRAINT fk_proame_on_amenity_entity FOREIGN KEY (amenity_id) REFERENCES amenity (id);

ALTER TABLE property_amenity_link
    ADD CONSTRAINT fk_proame_on_property_entity FOREIGN KEY (property_id) REFERENCES property (id);