server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-service:8081;
    }

    location /users/ {
        proxy_pass http://auth-service:8081;
    }

    location /recipes/ {
        proxy_pass http://recipe-service:8082;
    }

    location /comments/ {
        proxy_pass http://comment-service:8083;
    }
}