spring:
    application:
        name: ITMO-ACS-Backend

    datasource:
      url: jdbc:postgresql://localhost:5432/itmo-acs-backend
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: false #change when debug
      properties:
         hibernate:
           dialect: org.hibernate.dialect.PostgreSQLDialect
           format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /openapi.yaml
  api-docs:
    enabled: true
    path: /api-docs

jwt:
  access:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 900000  # 15 минут (миллисекунды)
  refresh:
    secret: 5265556A586E3272357538782F413F4428472B4B6250645367566B5970413F44
    expiration: 604800000  # 7 дней
  algorithm:

logging:
  level:
    com.petproject.itmoacsbackend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

server:
  port: 8080
  error:
#    include-stacktrace: always
#    include-message: always

