$kind: http-request
url: "{{baseUrl}}/applications/{{applicationId}}/status"
method: PATCH
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "status": "INVITED"
    }
auth:
  type: bearer
  credentials:
    token: "{{employerToken}}"
scripts:
  - type: afterResponse
    code: pm.test('200 and application status becomes INVITED', function () {
      pm.response.to.have.status(200); const j = pm.response.json();
      pm.expect(j.id).to.eql(pm.collectionVariables.get('applicationId'));
      pm.expect(j.vacancy_id).to.eql(pm.collectionVariables.get('vacancyId'));
      pm.expect(j.status).to.eql('INVITED'); });
    language: text/javascript
order: 20000
