services:
  catalog-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: catalog_db
    volumes:
      - catalog_db:/var/lib/postgresql/data
      - ./init-dbs/init_catalog.sql:/docker-entrypoint-initdb.d/init_catalog.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  booking-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: booking_db
    volumes:
      - booking_db:/var/lib/postgresql/data
      - ./init-dbs/init_booking.sql:/docker-entrypoint-initdb.d/init_booking.sql:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: auth_db
    volumes:
      - auth_db:/var/lib/postgresql/data
      - ./init-dbs/init_auth.sql:/docker-entrypoint-initdb.d/init_auth.sql:ro
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  review-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: review_db
    volumes:
      - review_db:/var/lib/postgresql/data
      - ./init-dbs/init_review.sql:/docker-entrypoint-initdb.d/init_review.sql:ro
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d review_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  auth-service:
    build: ./auth
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgres://postgres:a@auth-db:5432/auth_db?sslmode=disable
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/ping"]
      interval: 20s
      timeout: 1s
      retries: 10
      start_period: 1s
    restart: on-failure
    depends_on:
      auth-db:
        condition: service_healthy

  catalog-service:
    build: ./catalog
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgres://postgres:a@catalog-db:5432/catalog_db?sslmode=disable"
      BOOKING_SERVICE_URL: "http://booking-service:8003"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8002/ping"]
      interval: 20s
      timeout: 1s
      retries: 10
      start_period: 1s
    restart: on-failure
    depends_on:
      catalog-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  booking-service:
    build: ./booking
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: "postgres://postgres:a@booking-db:5432/booking_db?sslmode=disable"
      CATALOG_SERVICE_URL: "http://catalog-service:8002"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8003/ping"]
      interval: 20s
      timeout: 1s
      retries: 10
      start_period: 1s
    restart: on-failure
    depends_on:
      booking-db:
        condition: service_healthy
      catalog-service:
        condition: service_healthy

  review-service:
    build: ./review
    ports:
      - "8004:8004"
    environment:
      DATABASE_URL: postgres://postgres:a@review-db:5432/review_db?sslmode=disable
      CATALOG_SERVICE_URL: "http://catalog-service:8002"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8004/ping"]
      interval: 20s
      timeout: 1s
      retries: 10
      start_period: 1s
    restart: on-failure
    depends_on:
      review-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: 52-secret-key-67
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/ping"]
      interval: 20s
      timeout: 1s
      retries: 10
      start_period: 1s
    restart: on-failure
    depends_on:
      - auth-service
      - booking-service
      - catalog-service
      - review-service

  review-init:
    image: curlimages/curl:8.8.0
    entrypoint: ["sh", "/insert.sh"]
    volumes:
      - ./init-dbs/init_review_insert.sh:/insert.sh:ro
    restart: no
    depends_on:
      - gateway

volumes:
  catalog_db:
  booking_db:
  auth_db:
  review_db:
