services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lab3-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - recipe-network

  auth-service:
    build:
      context: .
      dockerfile: cmd/auth-service/Dockerfile
    container_name: lab3-auth-service
    ports:
      - "8081:8081"
    networks:
      - recipe-network

  recipe-service:
    build:
      context: .
      dockerfile: cmd/recipe-service/Dockerfile
    container_name: lab3-recipe-service
    ports:
      - "8082:8082"
    environment:
      RABBITMQ_API_URL: http://rabbitmq:15672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: recipe-events
    depends_on:
      - rabbitmq
    networks:
      - recipe-network

  social-service:
    build:
      context: .
      dockerfile: cmd/social-service/Dockerfile
    container_name: lab3-social-service
    ports:
      - "8083:8083"
    environment:
      RABBITMQ_API_URL: http://rabbitmq:15672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: recipe-events
    depends_on:
      - rabbitmq
    networks:
      - recipe-network

  api-gateway:
    build:
      context: .
      dockerfile: cmd/api-gateway/Dockerfile
    container_name: lab3-api-gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      RECIPE_SERVICE_URL: http://recipe-service:8082
      SOCIAL_SERVICE_URL: http://social-service:8083
    depends_on:
      - auth-service
      - recipe-service
      - social-service
    networks:
      - recipe-network

networks:
  recipe-network:
    driver: bridge
