services:
  auth-db:
    image: postgres:16
    container_name: lab2-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_db
      POSTGRES_PASSWORD: auth_db
    ports:
      - "15433:5432"
    volumes:
      - ./dbs/auth-postgres-data:/var/lib/postgresql/data

  recipe-db:
    image: postgres:16
    container_name: lab2-recipe-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_db
      POSTGRES_PASSWORD: recipe_db
    ports:
      - "15434:5432"
    volumes:
      - ./dbs/recipe-postgres-data:/var/lib/postgresql/data

  interaction-db:
    image: postgres:16
    container_name: lab2-interaction-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: interaction_db
      POSTGRES_USER: interaction_db
      POSTGRES_PASSWORD: interaction_db
    ports:
      - "15435:5432"
    volumes:
      - ./dbs/interaction-postgres-data:/var/lib/postgresql/data
